"""Progam: Matching Coins Game - Player Module
Author: Brandon Barrett
Description: This file contains the could necessary for the player in the main game file
Date: September 27, 2026"""

import coin
"""The coin neccessary for the player to be able to interact with coin objects"""


class Player:
    def __init__(self, name="Player1"):
        """This class represents a player. A player has a name, has a wallet of coins, and has a Coin object to toss"""
        self.__name = name
        self.__wallet = 20
        self.__coin = coin.Coin()

    def toss_coin(self):
        """Runs the toss method from the coin class to get a random value of 0 or 1"""
        self.__coin.toss()

    def get_coin_side(self):
        """Returns with the coin is heads(0) or tails(1) based on the number generated by the toss_coin method"""
        return self.__coin.get_sideup()

    def win_coin(self):
        """Adds a coin to the players wallet if they win a round"""
        self.__wallet += 1

    def lose_coin(self):
        """Removes a coin from the players wallet if they lose a round"""
        self.__wallet -= 1

    def get_wallet(self):
        """Returns the players wallet value"""
        return self.__wallet

    def get_name(self):
        return self.__name
